### ISSUE TITLE
Problems with the annual variability

### ISSUE THREAD

**Issue by carlesbene** [guillaumeevin/GWEX#1]
[WG_issue_for_GE.xlsx](https://github.com/guillaumeevin/GWEX/files/5621355/WG_issue_for_GE.xlsx)

Dear Guillaume,

First of all, I would like to congratulate you for such a nice tool. We are using your weather generator in our research here in Spain and actually we just published some of our results with GWEX (https://www.mdpi.com/2073-4441/12/11/3174). We are now moving forward and our next research is focused on the analysis of the sample uncertainty, and here is where we found a potential issue

Analysing the observed precipitation against the simulated with GWEX, we have noticed that the weather generator is not reproducing adequately the annual variability of the rainfall. In our case, we have simulated 5,000 years of precipitation for three different scenarios: 1) leaving the shape parameter as per default: 2) modifying this parameter to 0.11 over the months of SON for all grids and: 3) modifying this parameter to 0.2 over the months of SON for all grids.
As you can see in the attached for our study area, the simulated annual precipitation is uniformly distributed through all months, not considering the differences between the observed wettest months (SON) and the driest (JJA). Furthermore, observed wettest days of the year usually take place over the months of SON and again GWEX does not account for this, having all months the same probability to present the highest precipitation. Since we are manually forcing the xi parameter for these months, we would expect to find that SON are the wettest months and the one when most of the max. annual values take place.

We have already tried to simulate scenarios without using the disaggregator to see if this was the problem, but nothing with regards to the annual variability substantially changed. We were wondering if this is something we are doing wrong (maybe there is some list option we are not considering) or something that directly GWEX does not account for, in this case, could this have any solution?

Best Regards,

Carles

**Comment by guillaumeevin** [comment]
Problem with the assignment of dates.
