### ISSUE TITLE
Error in uniroot function when running GwexModel

### ISSUE THREAD

**Issue by RaffaeleUPV** [guillaumeevin/GWEX#5]
Good evening,

Error in uniroot(f, c(rho.emp, 1), extendInt = "upX", tol = 0.001) :    f.lower = f(lower) is NA appears when running the itGwexModel.
When running line 82 I get the error. I'm not sure how to solve this error. Any ideas on the cause, thx?

[uniroot_issue.zip](https://github.com/guillaumeevin/GWEX/files/14562454/uniroot_issue.zip)

**Comment by guillaumeevin** [comment]
Sorry I did not answer earlier to your comment. I will try to investigate this issue in the next days.

**Comment by guillaumeevin** [comment]
In your example, it seems that the parameters are estimated with only one year of data, which is not enough to identidy all the parameters.
